import { VK_ADS_API_BASE_URL } from "./config.js";
import { validateAdvertisingDestination } from "./destination-policy.js";

const VK_ADS_API_V3_BASE_URL = "https://ads.vk.com/api/v3" as const;
const VK_ADS_API_V1_BASE_URL = "https://ads.vk.com/api/v1" as const;

export type VkObject = Record<string, unknown>;

export interface VkPagedResponse<T extends VkObject = VkObject> {
  count: number;
  offset: number;
  items: T[];
}

export type StatisticsObjectType = "ad_plans" | "campaigns" | "ad_groups" | "banners" | "users";
export type StatisticsPeriod = "summary" | "day";
export type InAppStatisticsObjectType = "ad_plans" | "ad_groups" | "banners" | "users";
export type OfflineStatisticsObjectType = "ad_plans" | "ad_groups" | "users";
export type FastStatisticsObjectType = "ad_plans" | "banners" | "campaigns" | "users";
export type GoalStatisticsObjectType = "banners" | "ad_groups" | "ad_plans" | "users";

export interface VkStatisticsResponse extends VkObject {
  items: VkObject[];
  total: VkObject;
}

export const VERIFIED_AD_PLAN_FIELDS = [
  "ad_groups", "ad_object_id", "ad_object_type", "autobidding_mode", "bls", "budget_limit", "budget_limit_day", "budget_optimization_enabled", "campaigns", "created", "date_end", "date_start", "delivery", "docs_uploaded", "efficiency_status", "enable_offline_goals", "event_limit", "from_ads_easy_promote_mobile", "from_ads_easy_promote_web", "id", "issues", "lead_form_id", "max_price", "metric_statuses", "name", "objective", "objective_group", "or_migrated", "or_status", "origin_user_id", "package_id", "price", "priced_goal", "pricelist_id", "selling_proposition", "smart", "stats_info", "status", "targetings", "uniq_shows_limit", "uniq_shows_period", "updated", "vk_campaign_id", "vkads_migrated", "vkads_status", "yclients_salon_id",
] as const;

export const VERIFIED_AD_GROUP_FIELDS = [
  "ad_plan", "ad_plan_id", "age_restrictions", "audit_pixels", "audit_viewability", "autobidding_mode", "banner_uniq_shows_limit", "banners", "budget_limit", "budget_limit_day", "budget_optimization_enabled", "can_change_not_ad", "conversion_funnel_id", "created", "date_end", "date_start", "delivery", "documents", "dooh_settings", "dynamic_banners_use_storelink", "dynamic_without_remarketing", "efficiency_status", "enable_clickid", "enable_look_alike", "enable_offline_goals", "enable_ok_social_wrapper", "enable_recombination", "enable_utm", "event_limit", "external_id", "from_ads_easy_promote_mobile", "from_ads_easy_promote_web", "from_export_vkcom", "id", "interactions", "interface_read_only", "issues", "language", "learning_progress", "marketplace_app_client_id", "mask", "max_price", "mixing", "name", "not_ad", "objective", "or_migrated", "or_status", "ozon_s2s_pixel", "package_id", "package_priced_event_type", "pads_ots_limits", "panel_id", "price", "priced_goal", "pricelist_id", "pricelist_offer_group_id", "pricelist_tactic_id", "prices", "qsub", "read_only", "search_phrase_vectorization", "shows_limit", "sk_ad_campaign_id", "social", "social_quota", "stats_info", "status", "targeting_recommendation", "targetings", "ui_position", "uniq_shows_limit", "uniq_shows_period", "updated", "user_id", "utm", "vk_ext_mapping_id", "vkads_status",
] as const;

export const VERIFIED_BANNER_FIELDS = [
  "ad_group_id", "ad_plan_id", "autofaq_ticket_created", "blocked_patterns", "call_to_action",
  "campaign_id", "category", "content", "content_settings", "created", "deeplink", "delivery",
  "disc_id", "efficiency_status", "from_ads_easy_promote_mobile", "from_ads_easy_promote_web", "id",
  "is_autogenerated", "issues", "lead_form", "moderation_reasons", "moderation_status", "name",
  "or_status", "ord_marker", "pending_autofaq", "preview_image", "products", "settings", "stats_info",
  "status", "textblocks", "ui_position", "updated", "urls", "user_can_request_remoderation", "video_params",
  "vk_preview_link", "vk_video_preview_link", "vkads_status",
 ] as const;

const verifiedAdPlanFields = new Set<string>(VERIFIED_AD_PLAN_FIELDS);
const verifiedAdGroupFields = new Set<string>(VERIFIED_AD_GROUP_FIELDS);
const verifiedBannerFields = new Set<string>(VERIFIED_BANNER_FIELDS);

export interface VkAdsClientOptions {
  tokenProvider: () => string;
  tokenRefresher?: () => Promise<string>;
  timeoutMs: number;
  fetchImplementation?: typeof fetch;
  /** Общая очередь на credential. Необязательна, чтобы unit-тесты не ждали секунду. */
  waitForRequest?: () => Promise<void>;
  /** Внедряется в тестах; production использует ограниченную паузу после 429. */
  sleep?: (milliseconds: number) => Promise<void>;
}

export class VkAdsApiError extends Error {
  constructor(
    public readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = "VkAdsApiError";
  }
}

const allowedPaths = new Set([
  "/user.json",
  "/ad_plans.json",
  "/ad_groups.json",
  "/campaigns.json",
  "/banners.json",
  "/banner_patterns.json",
  "/banner_formats.json",
  "/banner_fields.json",
  "/packages.json",
  "/currencies.json",
  "/remarketing/counters.json",
  "/remarketing/inapp_events.json",
  "/remarketing/offline_goals.json",
  "/remarketing/pricelists.json",
  "/remarketing/segments.json",
  "/remarketing/local_geo.json",
  "/billing/transaction_groups.json",
  "/packages_pads.json",
  "/targetings_tree.json",
  "/pads_trees.json",
  "/mobile_categories.json",
  "/mobile_operators.json",
  "/mobile_types.json",
  "/mobile_os.json",
  "/mobile_vendors.json",
  "/throttling.json",
  "/regions.json",
  "/goals.json",
  "/agency/clients.json",
  "/sharing_keys.json",
  "/user_geo.json",
  "/ord_user.json",
  "/ord/agency/acts.json",
  "/ord/agency/report.json",
  "/ord/agency/status.json",
]);

const entityDetailPath = /^\/(ad_plans|campaigns|ad_groups|banners)\/(\d+)\.json$/;
const urlDetailPath = /^\/urls\/\d+(?:,\d+)*\.json$/;
const segmentDetailPath = /^\/remarketing\/segments\/\d+\.json$/;
const segmentRelationsPath = /^\/remarketing\/segments\/\d+\/relations\.json$/;
const remarketingCounterDetailPath = /^\/remarketing\/counters\/\d+\.json$/;
const counterGoalsPath = /^\/remarketing\/counters\/\d+\/goals\.json$/;
const counterGoalDetailPath = /^\/remarketing\/counters\/\d+\/goals\/\d+\.json$/;
const remarketingUserListDetailPath = /^\/remarketing\/users_lists\/\d+\.json$/;
const localGeoDetailPath = /^\/remarketing\/local_geo\/\d+\.json$/;
const pricelistDetailPath = /^\/remarketing\/pricelists\/\d+\.json$/;
const pricelistBatchPath = /^\/remarketing\/pricelists\/\d+\/batch\.json$/;
const customReportDetailPath = /^\/reports\/\d+\.json$/;
const appleAppPath = /^\/apple_apps\/\d+\.json$/;
const googleAppPath = /^\/google_apps\/[A-Za-z0-9][A-Za-z0-9._-]{0,254}\.json$/;
const leadExportPath = /^\/lead_ads\/lead_forms\/\d+\/leads\.(csv|xlsx)$/;
const surveyRespondentsExportPath = /^\/lead_ads\/survey_forms\/\d+\/respondents\.xlsx$/;
const sharingKeyPath = /^\/sharing_keys\/[A-Za-z0-9_-]{1,128}\.json$/;
const skAdNetworkPath = /^\/apple_apps\/\d+\/sk_ad_network_ids\/(share|withdraw)\.json$/;
const inAppEventCategoryPath = /^\/remarketing\/inapp_events\/\d+\/trackers\/\d+\/events\/\d+\.json$/;
const MAX_LEAD_EXPORT_BYTES = 25 * 1024 * 1024;

function isAllowedPath(path: string): boolean {
  return allowedPaths.has(path) || entityDetailPath.test(path) || urlDetailPath.test(path) || segmentDetailPath.test(path) || segmentRelationsPath.test(path) || remarketingCounterDetailPath.test(path) || counterGoalsPath.test(path) || remarketingUserListDetailPath.test(path) || localGeoDetailPath.test(path) || pricelistDetailPath.test(path) || pricelistBatchPath.test(path) || appleAppPath.test(path) || googleAppPath.test(path) || /^\/ord\/agency\/\d+\/acts\.json$/.test(path) || /^\/statistics\/(ad_plans|campaigns|ad_groups|banners|users)\/(summary|day)\.json$/.test(path) || /^\/statistics\/goals\/(banners|ad_groups|ad_plans|users)\/day\.json$/.test(path) || /^\/statistics\/inapp\/(ad_plans|ad_groups|banners|users)\/day\.json$/.test(path) || /^\/statistics\/offline_conversions\/(ad_plans|ad_groups|users)\/day\.json$/.test(path);
}

export class VkAdsClient {
  private readonly fetchImplementation: typeof fetch;

  constructor(private readonly options: VkAdsClientOptions) {
    this.fetchImplementation = options.fetchImplementation ?? fetch;
  }

  async getUser(): Promise<VkObject> {
    return this.get("/user.json");
  }

  async listAdPlans(offset = 0, limit = 100, fields?: string[], userId?: number): Promise<VkPagedResponse> {
    return this.getPaged("/ad_plans.json", offset, limit, { ...this.fieldsQuery(fields, verifiedAdPlanFields, "ad_plan"), ...this.userScopeQuery(userId) });
  }

  async listAdGroups(offset = 0, limit = 100, fields?: string[], userId?: number): Promise<VkPagedResponse> {
    return this.getPaged("/ad_groups.json", offset, limit, { ...this.fieldsQuery(fields, verifiedAdGroupFields, "ad_group"), ...this.userScopeQuery(userId) });
  }

  async listCampaigns(offset = 0, limit = 100, userId?: number): Promise<VkPagedResponse> {
    return this.getPaged("/campaigns.json", offset, limit, this.userScopeQuery(userId));
  }

  async listBanners(
    offset = 0,
    limit = 100,
    options: { adGroupId?: number; fields?: string[]; userId?: number } = {},
  ): Promise<VkPagedResponse> {
    if (options.adGroupId !== undefined) this.assertPositiveId(options.adGroupId);
    if (options.userId !== undefined) this.assertPositiveId(options.userId);
    if (options.fields !== undefined) {
      this.fieldsQuery(options.fields, verifiedBannerFields, "banner");
    }
    return this.getPaged("/banners.json", offset, limit, {
      ...(options.adGroupId !== undefined ? { _ad_group_id__in: String(options.adGroupId) } : {}),
      ...(options.fields ? { fields: options.fields.join(",") } : {}),
      ...this.userScopeQuery(options.userId),
    });
  }

  async listPackages(): Promise<VkObject[]> {
    return this.getItems("/packages.json");
  }

  async listPackagePads(): Promise<VkObject[]> {
    return this.getItems("/packages_pads.json");
  }

  async listCurrencies(): Promise<VkObject[]> {
    return this.getItems("/currencies.json");
  }

  async listBannerPatterns(): Promise<VkObject[]> {
    return this.getItems("/banner_patterns.json");
  }

  async listBannerFormats(): Promise<VkObject[]> {
    return this.getItems("/banner_formats.json");
  }

  async listBannerFieldDefinitions(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getPaged("/banner_fields.json", offset, limit);
  }

  async getAdPlan(id: number): Promise<VkObject> {
    return this.getEntity("ad_plans", id);
  }

  async getCampaign(id: number): Promise<VkObject> {
    return this.getEntity("campaigns", id);
  }

  async getAdGroup(id: number): Promise<VkObject> {
    return this.getEntity("ad_groups", id);
  }

  async getBanner(id: number): Promise<VkObject> {
    return this.getEntity("banners", id);
  }

  /** Ссылка уже встречается в `banner.urls.primary.id`; endpoint подтверждён live-пробой. */
  async getUrl(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.get(`/urls/${id}.json`);
  }

  /** Пакетное чтение уже зарегистрированных URL; новые URL не создаются. */
  async getUrls(ids: number[]): Promise<VkObject[]> {
    if (ids.length < 2 || ids.length > 50) throw new Error("ids должен содержать от 2 до 50 ID; для одного ID используйте getUrl.");
    ids.forEach((id) => this.assertPositiveId(id));
    return this.getItems(`/urls/${ids.join(",")}.json`);
  }

  /** Регистрирует HTTPS landing URL в VK Ads; MCP не выполняет запрос к этому URL. */
  async createUrl(url: string): Promise<VkObject> {
    const parsed = this.assertHttpsUrl(url);
    return this.post("/urls.json", { url: parsed.toString() });
  }

  async listRemarketingCounters(): Promise<VkObject[]> {
    return this.getItems("/remarketing/counters.json");
  }

  /** Документированное detail-чтение; права зависят от владельца счётчика. */
  async getRemarketingCounter(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.get(`/remarketing/counters/${id}.json`);
  }

  async renameTestRemarketingCounter(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestRemarketingCounter(id);
    return this.post(`/remarketing/counters/${id}.json`, { name });
  }

  async deleteTestRemarketingCounter(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestRemarketingCounter(id);
    return this.delete(`/remarketing/counters/${id}.json`);
  }

  async updateTestCounterGoal(input: { counterId: number; goalId: number; name: string; value: number; goalType: "content" | "search" | "basket" | "wishlist" | "checkout" | "payment_info" | "purchase" | "lead" | "registration" | "custom" }): Promise<VkObject> {
    this.assertPositiveId(input.counterId);
    this.assertPositiveId(input.goalId);
    this.assertTestName(input.name);
    if (!Number.isInteger(input.value) || input.value < -2_147_483_647 || input.value > 2_147_483_647) throw new Error("value цели должен быть целым числом в допустимом диапазоне.");
    await this.assertExistingTestRemarketingCounter(input.counterId);
    const goal = (await this.listRemarketingCounterGoals(input.counterId)).find((item) => Number(item.id) === input.goalId);
    if (!goal || typeof goal.name !== "string" || !goal.name.startsWith("__MCP_TEST__")) throw new Error("Разрешено изменить только существующую __MCP_TEST__ цель test-счётчика.");
    return this.post(`/remarketing/counters/${input.counterId}/goals/${input.goalId}.json`, { name: input.name, value: input.value, goal_type: input.goalType });
  }

  /** Официальный endpoint; доступ зависит от типа счётчика и роли credential. */
  async listRemarketingCounterGoals(counterId: number): Promise<VkObject[]> {
    this.assertPositiveId(counterId);
    return this.getItems(`/remarketing/counters/${counterId}/goals.json`);
  }

  /** Только metadata целей офлайн-конверсий; endpoint не содержит исходные события. */
  async listOfflineGoals(): Promise<VkObject[]> {
    return this.getItems("/remarketing/offline_goals.json");
  }

  async listPricelists(offset = 0, limit = 50): Promise<VkPagedResponse> {
    if (!Number.isInteger(limit) || limit < 1 || limit > 50) throw new Error("Для прайс-листов limit должен быть целым числом от 1 до 50.");
    return this.getPaged("/remarketing/pricelists.json", offset, limit);
  }

  /** API публикует список batch-задач, а не GET по отдельному task ID. */
  async listTestPricelistBatchTasks(pricelistId: number): Promise<VkObject[]> {
    this.assertPositiveId(pricelistId);
    await this.assertExistingTestPricelist(pricelistId);
    return this.getItems(`/remarketing/pricelists/${pricelistId}/batch.json`);
  }

  /** Один synthetic offer; только test-прайс-лист, URL проверяются локально. */
  async createTestPricelistBatchTask(input: { pricelistId: number; offerId: string; productType: string; title: string; link: string; imageLink: string; price: string }): Promise<VkObject[]> {
    this.assertPositiveId(input.pricelistId);
    await this.assertExistingTestPricelist(input.pricelistId);
    if (!/^[A-Za-z0-9._-]{1,100}$/.test(input.offerId)) throw new Error("offerId содержит недопустимые символы.");
    if (!/^[A-Za-z0-9._ -]{1,100}$/.test(input.productType) || input.title.trim().length < 1 || input.title.length > 150) throw new Error("Некорректные productType или title synthetic offer.");
    const link = this.assertHttpsUrl(input.link).toString();
    const imageLink = this.assertHttpsUrl(input.imageLink).toString();
    if (!/^\d+(?:\.\d{1,2})? [A-Z]{3}$/.test(input.price)) throw new Error("price должен иметь формат «100.00 RUB».");
    return this.postBatch(`/remarketing/pricelists/${input.pricelistId}/batch.json`, [{ method: "PUT", data: { id: input.offerId, product_type: input.productType, title: input.title.trim(), link, image_link: imageLink, price: input.price } }]);
  }

  /** Изменяет только изолированный test-каталог; рабочие каталоги и произвольные URL исключены. */
  async updateTestPricelist(input: { id: number; name: string; status: "active" | "blocked"; removeUtmTags: boolean; exportUrl?: string }): Promise<VkObject> {
    this.assertPositiveId(input.id);
    this.assertTestName(input.name);
    await this.assertExistingTestPricelist(input.id);
    const body: VkObject = { name: input.name, status: input.status, remove_utm_tags: input.removeUtmTags };
    if (input.exportUrl !== undefined) body.export_url = this.assertHttpsUrl(input.exportUrl).toString();
    return this.post(`/remarketing/pricelists/${input.id}.json`, body);
  }

  /** v3 отдаёт metadata списков; содержимое аудиторий намеренно не запрашивается. */
  async listRemarketingUserLists(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV3Paged("/remarketing/users_lists.json", offset, limit);
  }

  /** v2 detail нужен только для безопасной проверки test-имени перед write. */
  async getRemarketingUserList(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.get(`/remarketing/users_lists/${id}.json`);
  }

  /** Документированный multipart контракт. Сам файл валидирует уровень MCP. */
  async createTestRemarketingUserList(input: { name: string; type: string; filename: string; mimeType: "text/plain" | "text/csv"; bytes: Uint8Array }): Promise<VkObject> {
    this.assertTestName(input.name);
    if (!/^[a-z][a-z0-9_]{0,31}$/.test(input.type)) throw new Error("type списка ремаркетинга содержит недопустимые символы.");
    const form = new FormData();
    form.append("file", new Blob([new Uint8Array(input.bytes)], { type: input.mimeType }), input.filename);
    form.append("data", JSON.stringify({ name: input.name, type: input.type }));
    return this.postMultipart("/remarketing/users_lists.json", form);
  }

  async renameTestRemarketingUserList(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestRemarketingUserList(id);
    return this.post(`/remarketing/users_lists/${id}.json`, { name });
  }

  async deleteTestRemarketingUserList(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestRemarketingUserList(id);
    return this.delete(`/remarketing/users_lists/${id}.json`);
  }

  /** Документированный агентский контракт для уже существующего клиента. */
  async connectExistingAgencyClient(input: { userId: number; accessType: "full_access" }): Promise<VkObject> {
    this.assertPositiveId(input.userId);
    return this.post("/agency/clients.json", { access_type: input.accessType, user: { id: input.userId } });
  }

  async listInAppEvents(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getPaged("/remarketing/inapp_events.json", offset, limit);
  }

  async listInAppEventCategories(): Promise<VkObject[]> {
    return this.getV1Items("/inapp_event_categories.json");
  }

  /** Изменяет только категорию одного события по документированному v2 endpoint. */
  async updateInAppEventCategory(input: { appId: number; trackerId: number; eventId: number; categoryId: number }): Promise<void> {
    this.assertPositiveId(input.appId);
    this.assertPositiveId(input.trackerId);
    this.assertPositiveId(input.eventId);
    this.assertPositiveId(input.categoryId);
    await this.postNoContent(`/remarketing/inapp_events/${input.appId}/trackers/${input.trackerId}/events/${input.eventId}.json`, { inapp_event_category_id: input.categoryId });
  }

  /**
   * Связанные с приложениями пользователи и настройки атрибуции.
   * Ответ может содержать данные пользователей, поэтому публичную проекцию
   * выполняет MCP-слой и не возвращает массив users.
   */
  async listMobileAppUsers(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV1Paged("/mobile_app_users.json", offset, limit);
  }

  /** Технические поля нужны только для локального SKAdNetwork preflight. */
  async getAppleAppSkAdNetworkStatus(appId: number): Promise<VkObject> {
    this.assertPositiveId(appId);
    for (let offset = 0; offset < 2_000; offset += 50) {
      const page = await this.getV1Paged("/mobile_app_users.json", offset, 50, {
        fields: "app_name,platform,rb_mobile_app_id,campaign_ids,sk_ad_network_ids,users",
      });
      const app = page.items.find((item) => Number(item.rb_mobile_app_id) === appId && String(item.platform).toLowerCase() === "ios");
      if (app) return app;
      if (offset + page.items.length >= page.count) break;
    }
    throw new Error("Тестовое iOS-приложение не найдено среди приложений текущего credential.");
  }

  /** Список ключей шаринга; секреты ключей скрываются на уровне MCP. */
  async listSharingKeys(): Promise<VkObject[]> {
    return this.getItems("/sharing_keys.json");
  }

  /** Создаёт ключ только для test-сегмента; secret обрабатывается уровнем MCP. */
  async createTestSharingKey(input: { segmentId: number; recipient: string }): Promise<VkObject> {
    this.assertPositiveId(input.segmentId);
    await this.assertExistingTestSegment(input.segmentId);
    const recipient = input.recipient.trim();
    if (!recipient || recipient.length > 254 || /[\r\n]/.test(recipient)) throw new Error("Получатель ключа указан некорректно.");
    return this.post("/sharing_keys.json", { sources: [{ object_type: "segment", object_id: input.segmentId }], send_email: true, users: [{ username: recipient }] });
  }

  /** Ключ приходит только из памяти текущего MCP-сеанса, наружу не выводится. */
  async revokeSharingKey(key: string): Promise<VkObject> {
    if (!/^[A-Za-z0-9_-]{1,128}$/.test(key)) throw new Error("Формат ключа шаринга некорректен.");
    return this.delete(`/sharing_keys/${key}.json`);
  }

  async hasSharingKey(key: string): Promise<boolean> {
    if (!/^[A-Za-z0-9_-]{1,128}$/.test(key)) throw new Error("Формат ключа шаринга некорректен.");
    return (await this.listSharingKeys()).some((item) => item.sharing_key === key);
  }

  /** Только метаданные лид-форм: ответы и контакты респондентов не запрашиваются. */
  async listLeadForms(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV1Paged("/lead_ads/lead_forms.json", offset, limit);
  }

  /**
   * Полная конфигурация лид-формы. Контракт GET опубликован VK; MCP-слой
   * ниже отсекает реквизиты уведомлений и другие чувствительные поля.
   */
  async getLeadFormDetail(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.getV1(`/lead_ads/lead_forms/${id}.json`);
  }

  /** Копируется только уже изолированная test-форма; обычные формы исключены. */
  async copyTestLeadForm(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestLeadForm(id);
    return this.postV1(`/lead_ads/lead_forms/${id}/copy`, { name });
  }

  /**
   * Документированный POST позволяет менять всю конфигурацию формы. MCP
   * ограничивает его безопасным переименованием уже изолированной test-формы:
   * секции с контактами и уведомлениями не передаются и не могут быть стёрты.
   */
  async renameTestLeadForm(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestLeadForm(id);
    return this.postV1(`/lead_ads/lead_forms/${id}.json`, { name });
  }

  /** Тестовый лид не содержит пользовательских полей и допускается только для test-формы. */
  async sendTestLead(id: number): Promise<void> {
    this.assertPositiveId(id);
    await this.assertExistingTestLeadForm(id);
    await this.postV1(`/lead_ads/lead_forms/${id}/send_test_lead`, {});
  }

  async shareSkAdNetworkIds(input: { appId: number; count: number; recipient: string }): Promise<void> {
    this.assertPositiveId(input.appId);
    await this.postNoContent(`/apple_apps/${input.appId}/sk_ad_network_ids/share.json`, { count: input.count, username: input.recipient });
  }

  async withdrawSkAdNetworkIds(input: { appId: number; count: number; recipient: string }): Promise<void> {
    this.assertPositiveId(input.appId);
    await this.postNoContent(`/apple_apps/${input.appId}/sk_ad_network_ids/withdraw.json`, { count: input.count, username: input.recipient });
  }

  async archiveTestLeadForms(ids: number[], action: "archive" | "unarchive"): Promise<VkObject[]> {
    await this.assertTestLeadForms(ids);
    return this.postV1Array(`/lead_ads/lead_forms/${action}`, {}, { _form_ids__in: ids.join(",") });
  }

  /** Сырой ответ может содержать PII; его безопасная проекция выполняется уровнем MCP. */
  async listLeads(
    offset = 0,
    limit = 100,
    filters: { formIds?: number[]; adPlanIds?: number[]; adGroupIds?: number[]; bannerIds?: number[]; createdAtGte?: string; createdAtLte?: string } = {},
  ): Promise<VkPagedResponse> {
    const idsQuery = (ids: number[] | undefined, key: string): Record<string, string> => {
      if (!ids) return {};
      ids.forEach((id) => this.assertPositiveId(id));
      return { [key]: ids.join(",") };
    };
    return this.getV1Paged("/lead_ads/leads.json", offset, limit, {
      ...idsQuery(filters.formIds, "_form_ids__in"),
      ...idsQuery(filters.adPlanIds, "_ad_plan_ids__in"),
      ...idsQuery(filters.adGroupIds, "_ad_group_ids__in"),
      ...idsQuery(filters.bannerIds, "_banner_ids__in"),
      ...(filters.createdAtGte ? { "_created_at__gte": filters.createdAtGte } : {}),
      ...(filters.createdAtLte ? { "_created_at__lte": filters.createdAtLte } : {}),
    });
  }

  /**
   * Список респондентов опросов. Сырой ответ потенциально содержит ответы и
   * контакты, поэтому наружу он отдаётся только через безопасную проекцию MCP.
   */
  async listRespondents(
    offset = 0,
    limit = 100,
    filters: { formIds?: number[]; adPlanIds?: number[]; adGroupIds?: number[]; bannerIds?: number[]; createdAtGte?: string; createdAtLte?: string } = {},
  ): Promise<VkPagedResponse> {
    const idsQuery = (ids: number[] | undefined, key: string): Record<string, string> => {
      if (!ids) return {};
      ids.forEach((id) => this.assertPositiveId(id));
      return { [key]: ids.join(",") };
    };
    return this.getV1Paged("/lead_ads/respondents.json", offset, limit, {
      ...idsQuery(filters.formIds, "_form_ids__in"),
      ...idsQuery(filters.adPlanIds, "_ad_plan_ids__in"),
      ...idsQuery(filters.adGroupIds, "_ad_group_ids__in"),
      ...idsQuery(filters.bannerIds, "_banner_ids__in"),
      ...(filters.createdAtGte ? { _created_at__gte: filters.createdAtGte } : {}),
      ...(filters.createdAtLte ? { _created_at__lte: filters.createdAtLte } : {}),
    });
  }

  /** Возвращает PII только после отдельного preview/confirmation на уровне MCP. */
  async exportLeadFormLeads(input: {
    formId: number;
    format: "csv" | "xlsx";
    adPlanIds?: number[];
    adGroupIds?: number[];
    bannerIds?: number[];
    createdAtGte?: string;
    createdAtLte?: string;
  }): Promise<{ bytes: Uint8Array; contentType: string }> {
    this.assertPositiveId(input.formId);
    const idsQuery = (ids: number[] | undefined, key: string): Record<string, string> => {
      if (!ids) return {};
      ids.forEach((id) => this.assertPositiveId(id));
      return { [key]: ids.join(",") };
    };
    const path = `/lead_ads/lead_forms/${input.formId}/leads.${input.format}`;
    if (!leadExportPath.test(path)) throw new Error("Запрошен неразрешённый export path лидов.");
    const query = {
      ...idsQuery(input.adPlanIds, "_ad_plan_id__in"),
      ...idsQuery(input.adGroupIds, "_ad_group_id__in"),
      ...idsQuery(input.bannerIds, "_banner_id__in"),
      ...(input.createdAtGte ? { "_created_at__gte": input.createdAtGte } : {}),
      ...(input.createdAtLte ? { "_created_at__lte": input.createdAtLte } : {}),
    };
    const request = async (requestToken: string): Promise<Response> => {
      const url = new URL(`${VK_ADS_API_V1_BASE_URL}${path}`);
      for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
          headers: { Accept: input.format === "csv" ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось получить экспорт лидов из VK Ads API.");
      }
    };
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const response = await this.requestReadWithRetries(token, request);
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status} при экспорте лидов.`);
    const length = Number(response.headers.get("content-length"));
    if (Number.isFinite(length) && (length < 1 || length > MAX_LEAD_EXPORT_BYTES)) throw new Error("Размер экспорта лидов превышает локальный лимит 25 MiB.");
    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.length < 1 || bytes.length > MAX_LEAD_EXPORT_BYTES) throw new Error("Размер экспорта лидов должен быть от 1 байта до 25 MiB.");
    return { bytes, contentType: response.headers.get("content-type")?.split(";")[0] || (input.format === "csv" ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet") };
  }

  /** Возвращает PII только после отдельного preview/confirmation на уровне MCP. */
  async exportSurveyFormRespondents(formId: number): Promise<{ bytes: Uint8Array; contentType: string }> {
    this.assertPositiveId(formId);
    const path = `/lead_ads/survey_forms/${formId}/respondents.xlsx`;
    if (!surveyRespondentsExportPath.test(path)) throw new Error("Запрошен неразрешённый export path респондентов.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_V1_BASE_URL}${path}`, {
          headers: { Accept: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось получить экспорт респондентов из VK Ads API.");
      }
    };
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const response = await this.requestReadWithRetries(token, request);
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status} при экспорте респондентов.`);
    const length = Number(response.headers.get("content-length"));
    if (Number.isFinite(length) && (length < 1 || length > MAX_LEAD_EXPORT_BYTES)) throw new Error("Размер экспорта респондентов превышает локальный лимит 25 MiB.");
    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.length < 1 || bytes.length > MAX_LEAD_EXPORT_BYTES) throw new Error("Размер экспорта респондентов должен быть от 1 байта до 25 MiB.");
    return { bytes, contentType: response.headers.get("content-type")?.split(";")[0] || "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" };
  }

  /** Конфигурации опросов, без ответов респондентов и контактных данных. */
  async listSurveyForms(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV1Paged("/lead_ads/survey_forms.json", offset, limit);
  }

  /** См. getLeadFormDetail: безопасная проекция выполняется уровнем MCP. */
  async getSurveyFormDetail(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.getV1(`/lead_ads/survey_forms/${id}.json`);
  }

  /** Копируется только уже изолированный test-опрос; обычные опросы исключены. */
  async copyTestSurveyForm(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestSurveyForm(id);
    return this.postV1(`/lead_ads/survey_forms/${id}/copy`, { name });
  }

  async archiveTestSurveyForms(ids: number[], action: "archive" | "unarchive"): Promise<VkObject[]> {
    await this.assertTestSurveyForms(ids);
    return this.postV1Array(`/lead_ads/survey_forms/${action}`, {}, { _form_ids__in: ids.join(",") });
  }

  /** Capability-gated: обычный credential может получить 404/403. */
  async listUserGeo(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getPaged("/user_geo.json", offset, limit);
  }

  /** ОРД-данные пользователя; безопасная проекция выполняется MCP-слоем. */
  async getOrdUser(): Promise<VkObject> {
    return this.get("/ord_user.json");
  }

  /** ОРД партнёра доступен только credential с соответствующей ролью. */
  async listOrdPartnerPads(): Promise<VkObject> {
    return this.getV1("/ord/partner/pads.json");
  }

  async getOrdPartnerPad(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.getV1(`/ord/partner/pads/${id}.json`);
  }

  async listOrdPartnerSubagents(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV1Paged("/ord/partner/subagents.json", offset, limit);
  }

  async getOrdPartnerSubagent(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.getV1(`/ord/partner/subagents/${id}.json`);
  }

  async listOrdPartnerActs(month: string): Promise<VkObject> {
    this.assertMonthStart(month);
    return this.getV1(`/ord/partner/acts/${month}.json`);
  }

  /** ОРД-статистика конкретной площадки; sensitive fields очищает MCP-слой. */
  async getOrdPartnerActStatByPad(month: string, padId: number): Promise<VkObject> {
    this.assertMonthStart(month);
    this.assertPositiveId(padId);
    return this.getV1(`/ord/partner/acts/${month}/${padId}.json`);
  }

  async listOrdAgencyActs(month: string, offset = 0, limit = 100): Promise<VkPagedResponse> {
    this.assertMonthStart(month);
    return this.getPaged("/ord/agency/acts.json", offset, limit, { _month: month });
  }

  async getOrdAgencyClientActs(clientId: number, month: string, offset = 0, limit = 100): Promise<VkPagedResponse> {
    this.assertPositiveId(clientId);
    this.assertMonthStart(month);
    return this.getPaged(`/ord/agency/${clientId}/acts.json`, offset, limit, { _month: month });
  }

  async listOrdAgencyReports(month: string, offset = 0, limit = 100): Promise<VkPagedResponse> {
    this.assertMonthStart(month);
    return this.getPaged("/ord/agency/report.json", offset, limit, { _month: month });
  }

  async listOrdAgencyStatus(month: string, offset = 0, limit = 50): Promise<VkPagedResponse> {
    this.assertMonthStart(month);
    if (!Number.isInteger(limit) || limit < 1 || limit > 50) throw new Error("Для статусов ОРД агентства limit должен быть целым числом от 1 до 50.");
    return this.getPaged("/ord/agency/status.json", offset, limit, { _month: month });
  }

  async listSegments(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getPaged("/remarketing/segments.json", offset, limit);
  }

  async getSegment(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.get(`/remarketing/segments/${id}.json`);
  }

  async listSegmentRelations(id: number): Promise<VkObject[]> {
    this.assertPositiveId(id);
    return this.getItems(`/remarketing/segments/${id}/relations.json`);
  }

  /**
   * Контракт подтверждён live только для нового test-сегмента. Источник счётчика
   * читается, но не изменяется; сам сегмент обязательно получает test-префикс.
   */
  async createTestSegment(input: {
    name: string;
    counterSourceId: number;
    leftDays: number;
    goalId?: string;
  }): Promise<VkObject> {
    this.assertTestName(input.name);
    this.assertPositiveId(input.counterSourceId);
    this.assertSegmentDays(input.leftDays);
    return this.post("/remarketing/segments.json", {
      name: input.name,
      pass_condition: 1,
      relations: [{
        object_type: "remarketing_counter",
        params: {
          source_id: input.counterSourceId,
          goal_id: input.goalId ?? "",
          left: input.leftDays,
          right: 0,
          type: "positive",
        },
      }],
    });
  }

  /** Разрешено только для ранее созданного `__MCP_TEST__` сегмента. */
  async renameTestSegment(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestSegment(id);
    return this.post(`/remarketing/segments/${id}.json`, { name });
  }

  /** Удаляет только изолированный test-сегмент, не связанный с кампаниями. */
  async deleteTestSegment(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestSegment(id);
    return this.delete(`/remarketing/segments/${id}.json`);
  }

  /** Создаёт связь строго между двумя test-сегментами. */
  async addTestSegmentRelation(input: { segmentId: number; nestedSegmentId: number }): Promise<VkObject> {
    this.assertPositiveId(input.segmentId);
    this.assertPositiveId(input.nestedSegmentId);
    if (input.segmentId === input.nestedSegmentId) throw new Error("Нельзя вложить test-сегмент сам в себя.");
    await Promise.all([this.assertExistingTestSegment(input.segmentId), this.assertExistingTestSegment(input.nestedSegmentId)]);
    return this.post(`/remarketing/segments/${input.segmentId}/relations.json`, {
      items: [{ object_type: "segment", object_id: input.nestedSegmentId }],
    });
  }

  /** Удаляет связь только из test-сегмента; источник связи повторно сверяется. */
  async deleteTestSegmentRelation(input: { segmentId: number; relationId: number }): Promise<VkObject> {
    this.assertPositiveId(input.segmentId);
    this.assertPositiveId(input.relationId);
    await this.assertExistingTestSegment(input.segmentId);
    const relations = await this.listSegmentRelations(input.segmentId);
    if (!relations.some((relation) => Number(relation.id) === input.relationId)) {
      throw new Error("Связь сегмента не найдена в указанном test-сегменте.");
    }
    return this.delete(`/remarketing/segments/${input.segmentId}/relations/${input.relationId}.json`);
  }

  async listLocalGeo(): Promise<VkObject[]> {
    return this.getItems("/remarketing/local_geo.json");
  }

  /** Документированный контракт создания test local geo. */
  async createTestLocalGeo(input: { name: string; regions: Array<{ lat: number; lng: number; radius: number; label: string; address?: string }> }): Promise<VkObject> {
    this.assertTestName(input.name);
    if (input.regions.length < 1 || input.regions.length > 200) throw new Error("regions должен содержать от 1 до 200 точек.");
    for (const region of input.regions) {
      if (!Number.isFinite(region.lat) || region.lat < -90 || region.lat > 90 || !Number.isFinite(region.lng) || region.lng < -180 || region.lng > 180) {
        throw new Error("Координаты local geo выходят за допустимые границы.");
      }
      if (!Number.isInteger(region.radius) || region.radius < 1 || region.radius > 100_000) throw new Error("radius должен быть целым числом от 1 до 100000 метров.");
      if (!region.label.trim() || region.label.length > 200 || (region.address !== undefined && region.address.length > 500)) {
        throw new Error("label обязателен до 200 символов, address — не более 500 символов.");
      }
    }
    return this.post("/remarketing/local_geo.json", { name: input.name, regions: input.regions });
  }

  async updateTestLocalGeo(input: { id: number; name: string; regions: Array<{ lat: number; lng: number; radius: number; label: string; address?: string }> }): Promise<VkObject> {
    this.assertPositiveId(input.id);
    this.assertTestName(input.name);
    await this.assertExistingTestLocalGeo(input.id);
    return this.createOrUpdateTestLocalGeo(`/remarketing/local_geo/${input.id}.json`, input.name, input.regions);
  }

  async deleteTestLocalGeo(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestLocalGeo(id);
    return this.delete(`/remarketing/local_geo/${id}.json`);
  }

  private async createOrUpdateTestLocalGeo(path: string, name: string, regions: Array<{ lat: number; lng: number; radius: number; label: string; address?: string }>): Promise<VkObject> {
    if (regions.length < 1 || regions.length > 200) throw new Error("regions должен содержать от 1 до 200 точек.");
    for (const region of regions) {
      if (!Number.isFinite(region.lat) || region.lat < -90 || region.lat > 90 || !Number.isFinite(region.lng) || region.lng < -180 || region.lng > 180) {
        throw new Error("Координаты local geo выходят за допустимые границы.");
      }
      if (!Number.isInteger(region.radius) || region.radius < 1 || region.radius > 100_000) throw new Error("radius должен быть целым числом от 1 до 100000 метров.");
      if (!region.label.trim() || region.label.length > 200 || (region.address !== undefined && region.address.length > 500)) {
        throw new Error("label обязателен до 200 символов, address — не более 500 символов.");
      }
    }
    return this.post(path, { name, regions });
  }


  async listTransactionGroups(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getPaged("/billing/transaction_groups.json", offset, limit);
  }

  async getTargetingsTree(): Promise<VkObject> {
    return this.get("/targetings_tree.json");
  }

  async listPadsTree(): Promise<VkObject[]> {
    return this.getItems("/pads_trees.json");
  }

  async listMobileCategories(): Promise<VkObject[]> {
    return this.getItems("/mobile_categories.json");
  }

  async listMobileOperators(): Promise<VkObject[]> {
    return this.getItems("/mobile_operators.json");
  }

  async listMobileTypes(): Promise<VkObject[]> {
    return this.getItems("/mobile_types.json");
  }

  async listMobileOs(): Promise<VkObject[]> {
    return this.getItems("/mobile_os.json");
  }

  async listMobileVendors(): Promise<VkObject[]> {
    return this.getItems("/mobile_vendors.json");
  }

  async getMobileApp(input: { platform: "ios"; appId: number } | { platform: "android"; packageName: string }): Promise<VkObject> {
    if (input.platform === "ios") {
      this.assertPositiveId(input.appId);
      return this.get(`/apple_apps/${input.appId}.json`);
    }
    if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$/.test(input.packageName)) {
      throw new Error("Android package name содержит недопустимые символы.");
    }
    return this.get(`/google_apps/${input.packageName}.json`);
  }

  async getThrottling(): Promise<VkObject> {
    return this.get("/throttling.json");
  }

  /** Документированные фильтры справочника регионов; raw query passthrough запрещён. */
  async listRegions(
    offset = 0,
    limit = 100,
    filters: { query?: string; ids?: number[]; parentIds?: number[]; flags?: Array<"geo_tree" | "geo_tree_extended" | "rb_active"> } = {},
  ): Promise<VkPagedResponse> {
    if (!Number.isInteger(offset) || offset < 0) throw new Error("offset должен быть неотрицательным целым числом.");
    if (!Number.isInteger(limit) || limit < 1 || limit > 200) throw new Error("limit должен быть целым числом от 1 до 200.");
    if (filters.query !== undefined && (!filters.query.trim() || filters.query.length > 120)) throw new Error("query региона должен содержать от 1 до 120 символов.");
    filters.ids?.forEach((id) => this.assertPositiveId(id));
    filters.parentIds?.forEach((id) => {
      if (!Number.isInteger(id) || (id !== -1 && id <= 0)) throw new Error("parent_ids может содержать -1 или положительные ID.");
    });
    const payload = await this.get("/regions.json", {
      fields: "id,name,type",
      offset: String(offset),
      limit: String(limit),
      ...(filters.query !== undefined ? { _q: filters.query.trim() } : {}),
      ...(filters.ids?.length ? { _id__in: filters.ids.join(",") } : {}),
      ...(filters.parentIds?.length ? { _parent_id__in: filters.parentIds.join(",") } : {}),
      ...(filters.flags?.length ? { _flags__in: filters.flags.join(",") } : {}),
    });
    if (!Array.isArray(payload.items) || typeof payload.count !== "number") {
      throw new Error("VK Ads вернул неожиданный формат справочника регионов.");
    }
    return {
      count: payload.count,
      offset,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
    };
  }

  async getGoals(): Promise<VkObject> {
    return this.get("/goals.json");
  }

  async listAgencyClients(): Promise<VkObject[]> {
    return this.getItems("/agency/clients.json");
  }

  async listManagerClients(): Promise<VkObject[]> {
    const payload = await this.getV3("/manager/clients.json");
    if (!Array.isArray(payload.items)) throw new Error("VK Ads вернул неожиданный формат списка клиентов менеджера.");
    return payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null);
  }

  async listSearchPhrases(): Promise<VkObject[]> {
    return this.getV3Items("/search_phrases.json");
  }

  async listCustomReports(): Promise<VkObject[]> {
    return this.getV3Items("/reports.json");
  }

  async getCustomReport(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.getV3(`/reports/${id}.json`);
  }

  async createTestCustomReport(input: { title: string; metrics: string[]; slices: string[]; advertisers: number[]; dateFrom: string; dateTo: string }): Promise<VkObject> {
    this.assertTestName(input.title);
    input.advertisers.forEach((id) => this.assertPositiveId(id));
    return this.postV3("/reports.json", {
      title: input.title,
      metrics: input.metrics,
      slices: input.slices,
      conditions: { advertisers: input.advertisers, date_from: input.dateFrom, date_to: input.dateTo },
    });
  }

  async deleteTestCustomReport(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    const report = await this.getCustomReport(id);
    this.assertTestName(typeof report.title === "string" ? report.title : "");
    return this.deleteV3(`/reports/${id}.json`);
  }

  async listSubscriptions(offset = 0, limit = 100): Promise<VkPagedResponse> {
    return this.getV3Paged("/subscription.json", offset, limit);
  }

  async uploadStaticImage(input: { filename: string; mimeType: "image/png" | "image/jpeg" | "image/webp"; bytes: Uint8Array }): Promise<VkObject> {
    const form = new FormData();
    form.append("file", new Blob([new Uint8Array(input.bytes)], { type: input.mimeType }), input.filename);
    return this.postMultipart("/content/static.json", form);
  }

  /** HTML5 приходит одним проверенным ZIP-архивом; width/height VK получает из meta ad.size. */
  async uploadHtml5(input: { filename: string; bytes: Uint8Array }): Promise<VkObject> {
    const form = new FormData();
    form.append("file", new Blob([new Uint8Array(input.bytes)], { type: "application/zip" }), input.filename);
    return this.postMultipart("/content/html5.json", form);
  }

  /** Единственная роль, подтверждённая открытой документацией: logo. */
  async uploadLeadFormLogo(input: { filename: string; mimeType: "image/png" | "image/jpeg"; bytes: Uint8Array }): Promise<VkObject> {
    const form = new FormData();
    form.append("file", new Blob([new Uint8Array(input.bytes)], { type: input.mimeType }), input.filename);
    return this.postV1Multipart("/lead_ads/upload_image/logo", form);
  }

  /** Контракт подтверждён live: VK Ads требует multipart file и JSON data с размерами. */
  async uploadVideo(input: { filename: string; mimeType: "video/mp4"; bytes: Uint8Array; width: number; height: number }): Promise<VkObject> {
    this.assertVideoDimensions(input.width, input.height);
    const form = new FormData();
    form.append("file", new Blob([new Uint8Array(input.bytes)], { type: input.mimeType }), input.filename);
    form.append("data", JSON.stringify({ width: input.width, height: input.height }));
    return this.postMultipart("/content/video.json", form);
  }

  async createTestAdPlan(input: { name: string; objective: string; packageId: number }): Promise<VkObject> {
    this.assertTestName(input.name);
    this.assertPositiveId(input.packageId);
    return this.post("/ad_plans.json", {
      name: input.name,
      objective: input.objective,
      status: "blocked",
      campaigns: [{
        name: `${input.name} — campaign`,
        package_id: input.packageId,
        objective: input.objective,
        status: "blocked",
      }],
    });
  }

  /** Единственный подтверждённый direct-create campaign: blocked appinstalls package 2860 в test plan. */
  async createTestCampaign(input: { adPlanId: number; packageId: 2860; objective: "appinstalls"; name: string }): Promise<VkObject> {
    this.assertPositiveId(input.adPlanId);
    this.assertTestName(input.name);
    await this.assertExistingTestAdPlan(input.adPlanId);
    return this.post("/campaigns.json", {
      name: input.name,
      ad_plan_id: input.adPlanId,
      package_id: input.packageId,
      objective: input.objective,
      status: "blocked",
    });
  }

  async createTestAdGroup(input: { adPlanId: number; packageId: number; name: string; targetings: VkObject }): Promise<VkObject> {
    this.assertPositiveId(input.adPlanId);
    this.assertPositiveId(input.packageId);
    this.assertTestName(input.name);
    if (Object.keys(input.targetings).length === 0) throw new Error("targetings не может быть пустым.");
    await this.assertExistingTestAdPlan(input.adPlanId);
    return this.post("/ad_groups.json", {
      ad_plan_id: input.adPlanId,
      package_id: input.packageId,
      name: input.name,
      status: "blocked",
      targetings: input.targetings,
    });
  }

  /** Единственный live-проверенный шаблон banner: appinstalls package 2860, pattern 284. */
  async createTestBanner(input: {
    adGroupId: number;
    name: string;
    primaryUrlId: number;
    landscapeImageId: number;
    iconImageId: number;
    title: string;
    text: string;
    cta: "install";
  }): Promise<VkObject> {
    this.assertPositiveId(input.adGroupId);
    this.assertPositiveId(input.primaryUrlId);
    this.assertPositiveId(input.landscapeImageId);
    this.assertPositiveId(input.iconImageId);
    this.assertTestName(input.name);
    const group = await this.getAdGroup(input.adGroupId);
    this.assertTestName(typeof group.name === "string" ? group.name : "");
    if (Number(group.package_id) !== 2860) {
      throw new Error("Создание test banner пока подтверждено только для package_id=2860.");
    }
    await this.getUrl(input.primaryUrlId);
    return this.post(`/ad_groups/${input.adGroupId}/banners.json`, {
      name: input.name,
      status: "blocked",
      content: {
        image_1080x607: { id: input.landscapeImageId },
        icon_256x256_app: { id: input.iconImageId },
      },
      textblocks: {
        title_40_vkads: { text: input.title },
        text_90: { text: input.text },
        cta_apps_full: { text: input.cta },
      },
      urls: { primary: { id: input.primaryUrlId } },
    });
  }

  async renameTestAdGroup(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestAdGroup(id);
    return this.post(`/ad_groups/${id}.json`, { name });
  }

  /** Подтверждённый live-contract: rename только новой `__MCP_TEST__` campaign. */
  async renameTestCampaign(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestCampaign(id);
    return this.post(`/campaigns/${id}.json`, { name });
  }

  /** Используется только для изолированной очистки contract tests. */
  async deleteTestCampaign(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestCampaign(id);
    return this.post(`/campaigns/${id}.json`, { status: "deleted" });
  }

  /** Подтверждённый live-contract: rename только новой `__MCP_TEST__` banner. */
  async renameTestBanner(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestBanner(id);
    return this.post(`/banners/${id}.json`, { name });
  }

  /** Используется только для изолированной очистки contract tests. */
  async deleteTestBanner(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestBanner(id);
    return this.post(`/banners/${id}.json`, { status: "deleted" });
  }

  /**
   * Повторная модерация возможна только когда сам API явно разрешает её для
   * test-banner. При отсутствии флага запрос на запись не отправляется.
   */
  async remoderateTestBanners(ids: number[]): Promise<VkObject> {
    if (ids.length < 1 || ids.length > 200) throw new Error("ids должен содержать от 1 до 200 ID.");
    ids.forEach((id) => this.assertPositiveId(id));
    const banners = await Promise.all(ids.map(async (id) => ({ id, banner: await this.getBanner(id) })));
    await Promise.all(banners.map(({ id, banner }) => this.assertExistingTestBanner(id, banner)));
    if (banners.some(({ banner }) => banner.user_can_request_remoderation !== true)) {
      return {
        requested: false,
        results: banners.map(({ id: bannerId, banner: item }) => ({
          id: bannerId,
          remoderated: false,
          reason: item.user_can_request_remoderation === true ? "Не отправлено: batch содержит banner без права на remoderation." : "VK Ads не разрешил повторную модерацию этого banner.",
        })),
      };
    }
    return this.post("/banners/remoderate.json", { banners: ids.map((id) => ({ id })) }, { fields: "id,remoderated" });
  }

  async deleteTestAdGroup(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestAdGroup(id);
    return this.post(`/ad_groups/${id}.json`, { status: "deleted" });
  }

  async renameTestAdPlan(id: number, name: string): Promise<VkObject> {
    this.assertPositiveId(id);
    this.assertTestName(name);
    await this.assertExistingTestAdPlan(id);
    return this.post(`/ad_plans/${id}.json`, { name });
  }

  async deleteTestAdPlan(id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    await this.assertExistingTestAdPlan(id);
    return this.post(`/ad_plans/${id}.json`, { status: "deleted" });
  }

  /** Mass action разрешён только для остановки изолированных test ad plans. */
  async blockTestAdPlans(ids: number[]): Promise<VkObject> {
    if (ids.length < 1 || ids.length > 200) throw new Error("ids должен содержать от 1 до 200 ID.");
    ids.forEach((id) => this.assertPositiveId(id));
    await Promise.all(ids.map((id) => this.assertExistingTestAdPlan(id)));
    await this.postArray("/ad_plans/mass_action.json", ids.map((id) => ({ id, status: "blocked" })));
    return { ids, status: "blocked" };
  }

  /** Mass action разрешён только для остановки изолированных test ad groups. */
  async blockTestAdGroups(ids: number[]): Promise<VkObject> {
    if (ids.length < 1 || ids.length > 200) throw new Error("ids должен содержать от 1 до 200 ID.");
    ids.forEach((id) => this.assertPositiveId(id));
    await Promise.all(ids.map((id) => this.assertExistingTestAdGroup(id)));
    await this.postArray("/ad_groups/mass_action.json", ids.map((id) => ({ id, status: "blocked" })));
    return { ids, status: "blocked" };
  }

  /** Документированный batch contract; разрешена только остановка изолированных test banners. */
  async blockTestBanners(ids: number[]): Promise<VkObject> {
    if (ids.length < 1 || ids.length > 200) throw new Error("ids должен содержать от 1 до 200 ID.");
    ids.forEach((id) => this.assertPositiveId(id));
    await Promise.all(ids.map((id) => this.assertExistingTestBanner(id)));
    await this.postArray("/banners/mass_action.json", ids.map((id) => ({ id, status: "blocked" })));
    return { ids, status: "blocked" };
  }

  async getStatistics(input: {
    objectType: StatisticsObjectType;
    period: StatisticsPeriod;
    ids?: number[];
    dateFrom?: string;
    dateTo?: string;
    metrics?: string;
  }): Promise<VkStatisticsResponse> {
    if ((input.dateFrom === undefined) !== (input.dateTo === undefined)) {
      throw new Error("dateFrom и dateTo передаются только вместе.");
    }
    if (input.period === "day" && (!input.dateFrom || !input.dateTo)) {
      throw new Error("Для period=day VK Ads требует dateFrom и dateTo.");
    }
    const query: Record<string, string> = { metrics: input.metrics ?? "base" };
    if (input.ids?.length) query.id = input.ids.join(",");
    if (input.dateFrom && input.dateTo) {
      query.date_from = input.dateFrom;
      query.date_to = input.dateTo;
    }
    const payload = await this.get(`/statistics/${input.objectType}/${input.period}.json`, query);
    if (!Array.isArray(payload.items) || typeof payload.total !== "object" || payload.total === null || Array.isArray(payload.total)) {
      throw new Error("VK Ads вернул неожиданный формат статистики.");
    }
    return {
      ...payload,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
      total: payload.total as VkObject,
    };
  }

  /** Статистика конверсионных целей для планов, групп, баннеров или агрегата users. */
  async getGoalStatistics(input: { objectType: GoalStatisticsObjectType; ids: number[]; dateFrom: string; dateTo: string }): Promise<VkStatisticsResponse> {
    if (input.ids.length < 1 || input.ids.length > 50) throw new Error("ids должен содержать от 1 до 50 ID.");
    input.ids.forEach((id) => this.assertPositiveId(id));
    const payload = await this.get(`/statistics/goals/${input.objectType}/day.json`, {
      id: input.ids.join(","), date_from: input.dateFrom, date_to: input.dateTo,
    });
    if (!Array.isArray(payload.items) || typeof payload.total !== "object" || payload.total === null || Array.isArray(payload.total)) {
      throw new Error("VK Ads вернул неожиданный формат goal statistics.");
    }
    return {
      ...payload,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
      total: payload.total as VkObject,
    };
  }

  async getInAppStatistics(input: {
    objectType: InAppStatisticsObjectType;
    dateFrom: string;
    dateTo: string;
    ids?: number[];
    attribution?: "conversion" | "impression";
    conversionType?: "postclick" | "postview" | "total";
  }): Promise<VkStatisticsResponse> {
    const query: Record<string, string> = { date_from: input.dateFrom, date_to: input.dateTo };
    if (input.ids?.length) query.id = input.ids.join(",");
    if (input.attribution) query.attribution = input.attribution;
    if (input.conversionType) query.conversion_type = input.conversionType;
    const payload = await this.get(`/statistics/inapp/${input.objectType}/day.json`, query);
    if (!Array.isArray(payload.items) || typeof payload.total !== "object" || payload.total === null || Array.isArray(payload.total)) {
      throw new Error("VK Ads вернул неожиданный формат in-app статистики.");
    }
    return {
      ...payload,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
      total: payload.total as VkObject,
    };
  }

  async getOfflineConversionStatistics(input: {
    objectType: OfflineStatisticsObjectType;
    ids: number[];
    dateFrom: string;
    dateTo: string;
  }): Promise<{ items: VkObject[] }> {
    if (input.ids.length < 1 || input.ids.length > 50) throw new Error("ids должен содержать от 1 до 50 ID.");
    input.ids.forEach((id) => this.assertPositiveId(id));
    const payload = await this.get(`/statistics/offline_conversions/${input.objectType}/day.json`, {
      id: input.ids.join(","), date_from: input.dateFrom, date_to: input.dateTo,
    });
    if (!Array.isArray(payload.items)) throw new Error("VK Ads вернул неожиданный формат offline conversion statistics.");
    return { items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null) };
  }

  async getFastStatistics(objectType: FastStatisticsObjectType): Promise<VkObject> {
    return this.getV3(`/statistics/faststat/${objectType}.json`);
  }

  /** Прогноз охвата не создаёт кампанию, но расходует API-квоту; путь и payload фиксированы. */
  async getReachForecast(input: {
    packageIds?: number[];
    campaignId?: number;
    targetings: VkObject;
  }): Promise<VkObject> {
    const hasPackages = input.packageIds !== undefined;
    const hasCampaign = input.campaignId !== undefined;
    if (hasPackages === hasCampaign) throw new Error("Укажите packageIds или campaignId, но не оба поля.");
    input.packageIds?.forEach((id) => this.assertPositiveId(id));
    if (input.campaignId !== undefined) this.assertPositiveId(input.campaignId);
    if (!Array.isArray(input.targetings.pads) || input.targetings.pads.length < 1) {
      throw new Error("Для прогноза требуется непустой targetings.pads.");
    }
    return this.postV3("/projection.json", {
      ...(input.packageIds ? { package_ids: input.packageIds } : {}),
      ...(input.campaignId ? { campaign_id: input.campaignId } : {}),
      targetings: input.targetings,
    });
  }

  /** Проверяет audit pixel внутри VK Ads и возвращает допустимые производные роли. */
  async checkAuditPixel(auditPixel: string): Promise<VkObject> {
    const parsed = this.assertHttpsUrl(auditPixel);
    return this.postV3("/audit_pixel.json", { audit_pixel: parsed.toString() }, { fields: "audit_pixel,generated_audit_pixels" });
  }

  private async getPaged(path: string, offset: number, limit: number, extraQuery: Record<string, string> = {}): Promise<VkPagedResponse> {
    if (!Number.isInteger(offset) || offset < 0) throw new Error("offset должен быть неотрицательным целым числом.");
    if (!Number.isInteger(limit) || limit < 1 || limit > 200) throw new Error("limit должен быть целым числом от 1 до 200.");

    const payload = await this.get(path, { offset: String(offset), limit: String(limit), ...extraQuery });
    if (!Array.isArray(payload.items) || typeof payload.count !== "number" || typeof payload.offset !== "number") {
      throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    }

    return {
      count: payload.count,
      offset: payload.offset,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
    };
  }

  private async getEntity(entity: "ad_plans" | "campaigns" | "ad_groups" | "banners", id: number): Promise<VkObject> {
    this.assertPositiveId(id);
    return this.get(`/${entity}/${id}.json`);
  }

  private async getItems(path: string): Promise<VkObject[]> {
    const payload = await this.get(path);
    if (!Array.isArray(payload.items)) throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    return payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null);
  }

  private async assertExistingTestAdPlan(id: number): Promise<void> {
    const plan = await this.getAdPlan(id);
    this.assertTestName(typeof plan.name === "string" ? plan.name : "");
  }

  private async assertExistingTestAdGroup(id: number): Promise<void> {
    const group = await this.getAdGroup(id);
    this.assertTestName(typeof group.name === "string" ? group.name : "");
  }

  private async assertExistingTestCampaign(id: number): Promise<void> {
    const campaign = await this.getCampaign(id);
    this.assertTestName(typeof campaign.name === "string" ? campaign.name : "");
  }

  private async assertExistingTestBanner(id: number, knownBanner?: VkObject): Promise<void> {
    const banner = knownBanner ?? await this.getBanner(id);
    if (typeof banner.name === "string") {
      this.assertTestName(banner.name);
      return;
    }
    const adGroupId = Number(banner.ad_group_id);
    if (!Number.isInteger(adGroupId) || adGroupId <= 0) {
      throw new Error("VK Ads не вернул имя или ad_group_id banner; безопасно подтвердить test-объект невозможно.");
    }
    const page = await this.listBanners(0, 20, { adGroupId, fields: ["id", "name"] });
    const richBanner = page.items.find((item) => Number(item.id) === id);
    this.assertTestName(typeof richBanner?.name === "string" ? richBanner.name : "");
  }

  private async assertExistingTestSegment(id: number): Promise<void> {
    const segment = await this.getSegment(id);
    this.assertTestName(typeof segment.name === "string" ? segment.name : "");
  }

  private async assertExistingTestRemarketingUserList(id: number): Promise<void> {
    const list = await this.getRemarketingUserList(id);
    this.assertTestName(typeof list.name === "string" ? list.name : "");
  }

  private async assertExistingTestLocalGeo(id: number): Promise<void> {
    const localGeo = (await this.listLocalGeo()).find((item) => Number(item.id) === id);
    this.assertTestName(typeof localGeo?.name === "string" ? localGeo.name : "");
  }

  private async assertExistingTestPricelist(id: number): Promise<void> {
    for (let offset = 0; offset < 2_000; offset += 50) {
      const page = await this.listPricelists(offset, 50);
      const pricelist = page.items.find((item) => Number(item.id) === id);
      if (pricelist) {
        this.assertTestName(typeof pricelist.name === "string" ? pricelist.name : "");
        return;
      }
      if (offset + page.items.length >= page.count) break;
    }
    throw new Error("Прайс-лист не найден среди объектов текущего кабинета.");
  }

  private async assertExistingTestRemarketingCounter(id: number): Promise<void> {
    const counter = await this.getRemarketingCounter(id);
    this.assertTestName(typeof counter.name === "string" ? counter.name : "");
  }

  private async assertExistingTestLeadForm(id: number): Promise<void> {
    const form = await this.getLeadFormDetail(id);
    this.assertTestName(typeof form.name === "string" ? form.name : "");
  }

  private async assertExistingTestSurveyForm(id: number): Promise<void> {
    const form = await this.getSurveyFormDetail(id);
    this.assertTestName(typeof form.name === "string" ? form.name : "");
  }

  private async assertTestLeadForms(ids: number[]): Promise<void> {
    if (ids.length < 1 || ids.length > 50) throw new Error("ids должен содержать от 1 до 50 ID форм.");
    await Promise.all(ids.map((id) => this.assertExistingTestLeadForm(id)));
  }

  private async assertTestSurveyForms(ids: number[]): Promise<void> {
    if (ids.length < 1 || ids.length > 50) throw new Error("ids должен содержать от 1 до 50 ID форм.");
    await Promise.all(ids.map((id) => this.assertExistingTestSurveyForm(id)));
  }

  private assertTestName(name: string): void {
    if (!name.startsWith("__MCP_TEST__")) throw new Error("Разрешены только изолированные тестовые планы с именем __MCP_TEST__…");
  }

  private assertPositiveId(id: number): void {
    if (!Number.isInteger(id) || id <= 0) throw new Error("ID должен быть положительным целым числом.");
  }

  private assertMonth(value: string): void {
    if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(value)) throw new Error("month должен иметь формат YYYY-MM.");
  }

  private assertMonthStart(value: string): void {
    if (!/^\d{4}-(0[1-9]|1[0-2])-01$/.test(value)) throw new Error("month должен иметь формат YYYY-MM-01.");
  }

  private assertVideoDimensions(width: number, height: number): void {
    if (!Number.isInteger(width) || !Number.isInteger(height) || width < 1 || height < 1 || width > 16_384 || height > 16_384) {
      throw new Error("width и height должны быть целыми числами от 1 до 16384.");
    }
  }

  private assertSegmentDays(value: number): void {
    if (!Number.isInteger(value) || value < 1 || value > 365) {
      throw new Error("left_days должен быть целым числом от 1 до 365.");
    }
  }

  private assertHttpsUrl(value: string): URL {
    return new URL(validateAdvertisingDestination(value).url);
  }

  private userScopeQuery(userId: number | undefined): Record<string, string> {
    if (userId === undefined) return {};
    this.assertPositiveId(userId);
    return { _user_id: String(userId) };
  }

  private fieldsQuery(fields: string[] | undefined, allowedFields: Set<string>, entity: string): Record<string, string> {
    if (fields === undefined) return {};
    if (fields.length < 1 || fields.length > allowedFields.size) throw new Error(`fields должен содержать от 1 до ${allowedFields.size} полей ${entity}.`);
    if (fields.some((field) => !allowedFields.has(field))) throw new Error(`Запрошено неподтверждённое поле ${entity}.`);
    return { fields: fields.join(",") };
  }

  /** GET безопасно повторяется один раз после 429; write намеренно не повторяется автоматически. */
  private async requestReadWithRetries(initialToken: string, request: (token: string) => Promise<Response>): Promise<Response> {
    let token = initialToken;
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) {
      token = await this.options.tokenRefresher();
      response = await request(token);
    }
    if (response.status === 429) {
      await (this.options.sleep ?? ((milliseconds: number) => new Promise<void>((resolve) => setTimeout(resolve, milliseconds))))(this.retryAfterMilliseconds(response));
      response = await request(token);
      if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    }
    return response;
  }

  private retryAfterMilliseconds(response: Response): number {
    const raw = response.headers.get("retry-after")?.trim();
    if (!raw) return 1_000;
    const seconds = Number(raw);
    if (Number.isFinite(seconds) && seconds >= 0) return Math.min(Math.ceil(seconds * 1_000), 5_000);
    const timestamp = Date.parse(raw);
    if (Number.isFinite(timestamp)) return Math.min(Math.max(timestamp - Date.now(), 1_000), 5_000);
    return 1_000;
  }

  private async get(path: string, query: Record<string, string> = {}): Promise<VkObject> {
    if (!isAllowedPath(path)) throw new Error("Запрошен неразрешённый путь VK Ads API.");

    const url = new URL(`${VK_ADS_API_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);

    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");

    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
        method: "GET",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${requestToken}`,
        },
        signal: AbortSignal.timeout(this.options.timeoutMs),
        redirect: "error",
      });
      } catch {
        throw new Error("Не удалось выполнить запрос к VK Ads API.");
      }
    };

    const response = await this.requestReadWithRetries(token, request);

    if (!response.ok) {
      throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    }

    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) {
      throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    }
    return payload as VkObject;
  }

  private async getV3(path: string, query: Record<string, string> = {}): Promise<VkObject> {
    if (path !== "/manager/clients.json" && path !== "/remarketing/users_lists.json" && path !== "/search_phrases.json" && path !== "/subscription.json" && path !== "/reports.json" && !customReportDetailPath.test(path) && !/^\/statistics\/faststat\/(ad_plans|banners|campaigns|users)\.json$/.test(path)) {
      throw new Error("Запрошен неразрешённый v3-путь VK Ads API.");
    }
    const url = new URL(`${VK_ADS_API_V3_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");

    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
          method: "GET",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить запрос к VK Ads API.");
      }
    };

    const response = await this.requestReadWithRetries(token, request);
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async getV3Paged(path: string, offset: number, limit: number): Promise<VkPagedResponse> {
    if (!Number.isInteger(offset) || offset < 0) throw new Error("offset должен быть неотрицательным целым числом.");
    if (!Number.isInteger(limit) || limit < 1 || limit > 200) throw new Error("limit должен быть целым числом от 1 до 200.");
    const payload = await this.getV3(path, { offset: String(offset), limit: String(limit) });
    if (!Array.isArray(payload.items) || typeof payload.count !== "number" || typeof payload.offset !== "number") {
      throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    }
    return {
      count: payload.count,
      offset: payload.offset,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
    };
  }

  private async getV3Items(path: string): Promise<VkObject[]> {
    const payload = await this.getV3(path);
    if (!Array.isArray(payload.items)) throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    return payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null);
  }

  private async getV1(path: string, query: Record<string, string> = {}): Promise<VkObject> {
    if (path !== "/inapp_event_categories.json" && path !== "/mobile_app_users.json" && path !== "/lead_ads/lead_forms.json" && path !== "/lead_ads/leads.json" && path !== "/lead_ads/respondents.json" && path !== "/lead_ads/survey_forms.json" && !/^\/lead_ads\/(lead_forms|survey_forms)\/\d+\.json$/.test(path) && !/^\/ord\/partner\/(pads|subagents)\.json$/.test(path) && !/^\/ord\/partner\/(pads|subagents)\/\d+\.json$/.test(path) && !/^\/ord\/partner\/acts\/\d{4}-\d{2}-01(?:\/\d+)?\.json$/.test(path)) {
      throw new Error("Запрошен неразрешённый v1-путь VK Ads API.");
    }
    const url = new URL(`${VK_ADS_API_V1_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
          method: "GET",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить запрос к VK Ads API.");
      }
    };
    const response = await this.requestReadWithRetries(token, request);
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async postV1(path: string, body: VkObject): Promise<VkObject> {
    if (!/^\/lead_ads\/(lead_forms|survey_forms)\/\d+\/copy$/.test(path) && !/^\/lead_ads\/lead_forms\/\d+\/send_test_lead$/.test(path) && !/^\/lead_ads\/lead_forms\/\d+\.json$/.test(path)) throw new Error("Запрошен неразрешённый v1 write-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_V1_BASE_URL}${path}`, {
          method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить v1 write-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async postV1Array(path: string, body: VkObject, query: Record<string, string>): Promise<VkObject[]> {
    if (!/^\/lead_ads\/(lead_forms|survey_forms)\/(archive|unarchive)$/.test(path)) throw new Error("Запрошен неразрешённый v1 write-путь VK Ads API.");
    const url = new URL(`${VK_ADS_API_V1_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, { method: "POST", headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(this.options.timeoutMs), redirect: "error" });
      } catch {
        throw new Error("Не удалось выполнить v1 write-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (!Array.isArray(payload) || !payload.every((item) => typeof item === "object" && item !== null && !Array.isArray(item))) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject[];
  }

  private async postV1Multipart(path: string, body: FormData): Promise<VkObject> {
    if (path !== "/lead_ads/upload_image/logo") throw new Error("Запрошен неразрешённый v1 upload-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_V1_BASE_URL}${path}`, { method: "POST", headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` }, body, signal: AbortSignal.timeout(this.options.timeoutMs), redirect: "error" });
      } catch {
        throw new Error("Не удалось выполнить v1 upload-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async postBatch(path: string, body: VkObject[]): Promise<VkObject[]> {
    if (!pricelistBatchPath.test(path)) throw new Error("Запрошен неразрешённый batch-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string) => this.fetchImplementation(`${VK_ADS_API_BASE_URL}${path}`, { method: "POST", headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(this.options.timeoutMs), redirect: "error" });
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (!Array.isArray(payload) || !payload.every((item) => typeof item === "object" && item !== null && !Array.isArray(item))) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject[];
  }

  private async getV1Items(path: string): Promise<VkObject[]> {
    const payload = await this.getV1(path);
    if (!Array.isArray(payload.items)) throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    return payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null);
  }

  private async getV1Paged(path: string, offset: number, limit: number, extraQuery: Record<string, string> = {}): Promise<VkPagedResponse> {
    if (!Number.isInteger(offset) || offset < 0) throw new Error("offset должен быть неотрицательным целым числом.");
    if (!Number.isInteger(limit) || limit < 1 || limit > 200) throw new Error("limit должен быть целым числом от 1 до 200.");
    const payload = await this.getV1(path, { offset: String(offset), limit: String(limit), ...extraQuery });
    if (!Array.isArray(payload.items) || typeof payload.count !== "number") {
      throw new Error(`VK Ads вернул неожиданный формат списка для ${path}.`);
    }
    return {
      count: payload.count,
      offset: typeof payload.offset === "number" ? payload.offset : offset,
      items: payload.items.filter((item): item is VkObject => typeof item === "object" && item !== null),
    };
  }

  private async postV3(path: string, body: VkObject, query: Record<string, string> = {}): Promise<VkObject> {
    if (path !== "/projection.json" && path !== "/audit_pixel.json" && path !== "/reports.json") throw new Error("Запрошен неразрешённый v3 write-путь VK Ads API.");
    const url = new URL(`${VK_ADS_API_V3_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
          method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async deleteV3(path: string): Promise<VkObject> {
    if (!customReportDetailPath.test(path)) throw new Error("Запрошен неразрешённый v3 delete-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_V3_BASE_URL}${path}`, {
          method: "DELETE",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить v3 delete-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    if (response.status === 204 || response.headers.get("content-length") === "0") return {};
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async post(path: string, body: VkObject, query: Record<string, string> = {}): Promise<VkObject> {
    if (
      path !== "/ad_plans.json"
      && path !== "/campaigns.json"
      && path !== "/ad_groups.json"
      && path !== "/urls.json"
      && path !== "/remarketing/segments.json"
      && path !== "/remarketing/local_geo.json"
      && !pricelistDetailPath.test(path)
      && path !== "/agency/clients.json"
      && path !== "/sharing_keys.json"
      && !skAdNetworkPath.test(path)
      && path !== "/banners/remoderate.json"
      && !/^\/(ad_plans|campaigns|ad_groups|banners)\/\d+\.json$/.test(path)
      && !/^\/ad_groups\/\d+\/banners\.json$/.test(path)
      && !/^\/remarketing\/segments\/\d+(?:\/relations)?\.json$/.test(path)
      && !remarketingCounterDetailPath.test(path)
      && !counterGoalDetailPath.test(path)
      && !remarketingUserListDetailPath.test(path)
      && !localGeoDetailPath.test(path)
    ) {
      throw new Error("Запрошен неразрешённый write-путь VK Ads API.");
    }
    const url = new URL(`${VK_ADS_API_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value);
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(url, {
        method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(this.options.timeoutMs),
        redirect: "error",
      });
      } catch {
        throw new Error("Не удалось выполнить write-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    if (response.status === 204) return {};
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async postArray(path: string, body: VkObject[]): Promise<void> {
    if (path !== "/ad_plans/mass_action.json" && path !== "/ad_groups/mass_action.json" && path !== "/banners/mass_action.json") throw new Error("Запрошен неразрешённый mass-action путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_BASE_URL}${path}`, {
        method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(this.options.timeoutMs),
        redirect: "error",
      });
      } catch {
        throw new Error("Не удалось выполнить mass-action запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
  }

  private async delete(path: string): Promise<VkObject> {
    if (!/^\/remarketing\/segments\/\d+(?:\/relations\/\d+)?\.json$/.test(path) && !remarketingCounterDetailPath.test(path) && !remarketingUserListDetailPath.test(path) && !localGeoDetailPath.test(path) && !sharingKeyPath.test(path)) {
      throw new Error("Запрошен неразрешённый delete-путь VK Ads API.");
    }
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_BASE_URL}${path}`, {
          method: "DELETE",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` },
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить delete-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    if (response.status === 204 || response.headers.get("content-length") === "0") return {};
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }

  private async postNoContent(path: string, body: VkObject): Promise<void> {
    if (!skAdNetworkPath.test(path) && !inAppEventCategoryPath.test(path)) throw new Error("Запрошен неразрешённый high-risk write-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_BASE_URL}${path}`, {
          method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}`, "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(this.options.timeoutMs),
          redirect: "error",
        });
      } catch {
        throw new Error("Не удалось выполнить высокорисковый write-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
  }

  private async postMultipart(path: string, body: FormData): Promise<VkObject> {
    if (path !== "/content/static.json" && path !== "/content/video.json" && path !== "/content/html5.json" && path !== "/remarketing/users_lists.json") throw new Error("Запрошен неразрешённый upload-путь VK Ads API.");
    let token = this.options.tokenProvider();
    if (!token && this.options.tokenRefresher) token = await this.options.tokenRefresher();
    if (!token) throw new Error("Токен VK Ads пуст.");
    const request = async (requestToken: string): Promise<Response> => {
      try {
        await this.options.waitForRequest?.();
        return await this.fetchImplementation(`${VK_ADS_API_BASE_URL}${path}`, {
        method: "POST",
          headers: { Accept: "application/json", Authorization: `Bearer ${requestToken}` },
        body,
        signal: AbortSignal.timeout(this.options.timeoutMs),
        redirect: "error",
      });
      } catch {
        throw new Error("Не удалось выполнить upload-запрос к VK Ads API.");
      }
    };
    let response = await request(token);
    if (response.status === 401 && this.options.tokenRefresher) response = await request(await this.options.tokenRefresher());
    if (!response.ok) throw new VkAdsApiError(response.status, `VK Ads API вернул HTTP ${response.status}.`);
    const payload: unknown = await response.json();
    if (typeof payload !== "object" || payload === null || Array.isArray(payload)) throw new Error("VK Ads API вернул неожиданный JSON-ответ.");
    return payload as VkObject;
  }
}
